local Remap = require("leptanian.keyfn")
local nnoremap = Remap.nnoremap

nnoremap("<C-p>", ":Telescope ")
nnoremap("<leader>ff", function()
    require('telescope.builtin').find_files()
end)
nnoremap("<leader>fs", function()
    require('telescope.builtin').grep_string({ search = vim.fn.input("Grep For > ")})
end)

nnoremap("<leader>fw", function()
    require('telescope.builtin').grep_string { search = vim.fn.expand("<cword>") }
end)
nnoremap("<leader>fb", function()
    require('telescope.builtin').buffers()
end)
nnoremap("<leader>fh", function()
    require('telescope.builtin').help_tags()
end)
-- nnoremap("<C-p>", function()
--     require('telescope.builtin').git_files()
-- end)
-- nnoremap("<leader>vrc", function()
--     require('leptanian.telescope').search_dotfiles({ hidden = true })
-- end)
-- nnoremap("<leader>va", function()
--     require('leptanian.telescope').anime_selector()
-- end)
-- nnoremap("<leader>vc", function()
--     require('leptanian.telescope').chat_selector()
-- end)
-- nnoremap("<leader>gc", function()
--     require('leptanian.telescope').git_branches()
-- end)
-- nnoremap("<leader>gw", function()
--     require('telescope').extensions.git_worktree.git_worktrees()
-- end)
-- nnoremap("<leader>gm", function()
--     require('telescope').extensions.git_worktree.create_git_worktree()
-- end)
-- nnoremap("<leader>td", function()
--     require('leptanian.telescope').dev()
-- end)

